---

- name: Add admin user
  user: name="{{admin_username}}"
        shell=/bin/bash
        groups="sudo"

- name: Create /etc/sudoers.d/ folder if not exists
  file:
    path: /etc/sudoers.d/
    state: directory

- name: Check if user is already sudoer
  stat:
      path: "/etc/sudoers.d/{{ admin_username }}"
  register: sudoer

- name: "Make {{ admin_username }} sudoer if not already"
  file:
    path: "/etc/sudoers.d/{{ admin_username }}"
    state: touch
  when: sudoer.stat.exists == False

- name: Allow admin to have passwordless sudo
  lineinfile:
    dest: "/etc/sudoers.d/{{ admin_username }}"
    state: present
    line: '{{ admin_username }} ALL=(ALL) NOPASSWD: ALL'

- name: Push SSH keys to admin
  authorized_key: user={{admin_username}}
                  key="{{item}}"
  with_file:
      - "{{ admin_authorized_keys }}"
  when: admin_authorized_keys is defined
